export const ADD_WEATHER_ITEM = 'ADD_WEATHER_ITEM'
export const SET_PROCESSING_FLAG = 'SET_PROCESSING_FLAG'
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE'
export const ADD_SELECTED_DAY = 'ADD_SELECTED_DAY'

export const RESET_STATE = 'RESET_STATE'
